#ifndef _STORAGE_KEYS_H_
#define _STORAGE_KEYS_H_

#define STORAGE_UART_ENABLE "UART_ENABLE_%d"
#define STORAGE_UART_BAUDS "UART_BAUDS_%d"
#define STORAGE_UART_TCP_PORT "UART_TCP_PORT_%d"
#define STORAGE_UART_TX_PIN "UART_TX_PIN_%d"
#define STORAGE_UART_RX_PIN "UART_RX_PIN_%d"
#define STORAGE_UART_TX_BUFFER "UART_TX_BUFFER_%d"
#define STORAGE_UART_RX_BUFFER "UART_RX_BUFFER_%d"
#define STORAGE_UART_DATA_BITS "UART_DATA_BITS_%d"
#define STORAGE_UART_PARITY "UART_PARITY_%d"
#define STORAGE_UART_STOP_BITS "UART_STOP_BITS_%d"

#define STORAGE_WIFI_MODE "WIFI_MODE"
#define STORAGE_WIFI_SSID "WIFI_SSID"
#define STORAGE_WIFI_PASSWD "WIFI_PASSWD"
#define STORAGE_WIFI_CHANNEL "WIFI_CHANNEL"

#endif